"""catalogo y lecturas

Revision ID: 0003_catalogo_lecturas
"""
from alembic import op
import sqlalchemy as sa


revision = '0003_catalogo_lecturas'
down_revision = '0002_spanish_names'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('obras',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_language', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app.usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_obras_created_by_user_id'), 'obras', ['created_by_user_id'], unique=False, schema='app')
    op.create_table('ediciones',
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('edition_label', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.SmallInteger(), nullable=True),
    sa.Column('isbn13', sa.String(length=13), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('publisher_name', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('page_count > 0', name='ck_ediciones_page_count'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_id'], ['app.obras.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'work_id', name='uq_ediciones_id_work'),
    sa.UniqueConstraint('isbn13'),
    schema='app'
    )
    op.create_index(op.f('ix_app_ediciones_created_by_user_id'), 'ediciones', ['created_by_user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_ediciones_work_id'), 'ediciones', ['work_id'], unique=False, schema='app')
    op.create_table('entradas_biblioteca',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app.usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_id'], ['app.obras.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'work_id', name='uq_biblioteca_id_work'),
    sa.UniqueConstraint('user_id', 'work_id', name='uq_biblioteca_user_work'),
    schema='app'
    )
    op.create_index(op.f('ix_app_entradas_biblioteca_work_id'), 'entradas_biblioteca', ['work_id'], unique=False, schema='app')
    op.create_table('obras_autores',
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position > 0', name='ck_obras_autores_position'),
    sa.ForeignKeyConstraint(['author_id'], ['app.autores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_id'], ['app.obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_id', 'author_id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_obras_autores_author_id'), 'obras_autores', ['author_id'], unique=False, schema='app')
    op.create_table('fuentes_catalogo',
    sa.Column('edition_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['app.ediciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_fuentes_catalogo_provider_external'),
    schema='app'
    )
    op.create_index(op.f('ix_app_fuentes_catalogo_edition_id'), 'fuentes_catalogo', ['edition_id'], unique=False, schema='app')
    op.create_table('lecturas',
    sa.Column('library_entry_id', sa.Uuid(), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('edition_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('current_page', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('abandoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('abandonment_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'abandoned' AND abandoned_at IS NOT NULL AND abandonment_reason IS NOT NULL AND length(trim(abandonment_reason)) > 0 AND abandoned_at >= started_at) OR (status <> 'abandoned' AND abandoned_at IS NULL AND abandonment_reason IS NULL)", name='ck_lecturas_abandoned'),
    sa.CheckConstraint("(status = 'finished' AND finished_at IS NOT NULL AND current_page = total_pages AND finished_at >= started_at) OR (status <> 'finished' AND finished_at IS NULL)", name='ck_lecturas_finished'),
    sa.CheckConstraint("(status = 'pending' AND current_page = 0 AND started_at IS NULL) OR (status <> 'pending' AND total_pages IS NOT NULL AND started_at IS NOT NULL)", name='ck_lecturas_started'),
    sa.CheckConstraint("status IN ('pending', 'reading', 'finished', 'abandoned')", name='ck_lecturas_status'),
    sa.CheckConstraint('current_page >= 0 AND (total_pages IS NULL OR (total_pages > 0 AND current_page <= total_pages))', name='ck_lecturas_pages'),
    sa.ForeignKeyConstraint(['edition_id', 'work_id'], ['app.ediciones.id', 'app.ediciones.work_id'], name='fk_lecturas_edicion_obra', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['library_entry_id', 'work_id'], ['app.entradas_biblioteca.id', 'app.entradas_biblioteca.work_id'], name='fk_lecturas_biblioteca_obra', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_lecturas_edition_id'), 'lecturas', ['edition_id'], unique=False, schema='app')
    op.create_index('ix_lecturas_biblioteca_created', 'lecturas', ['library_entry_id', 'created_at'], unique=False, schema='app')
    op.create_table('progreso_lectura',
    sa.Column('reading_id', sa.Uuid(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('page >= 0', name='ck_progreso_lectura_page'),
    sa.ForeignKeyConstraint(['reading_id'], ['app.lecturas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('ix_progreso_lectura_recorded', 'progreso_lectura', ['reading_id', 'recorded_at'], unique=False, schema='app')
    op.drop_constraint(op.f('auth_accounts_email_key'), 'cuentas_autenticacion', schema='app', type_='unique')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('auth_accounts_email_key'), 'cuentas_autenticacion', ['email'], schema='app', postgresql_nulls_not_distinct=False)
    op.drop_index('ix_progreso_lectura_recorded', table_name='progreso_lectura', schema='app')
    op.drop_table('progreso_lectura', schema='app')
    op.drop_index('ix_lecturas_biblioteca_created', table_name='lecturas', schema='app')
    op.drop_index(op.f('ix_app_lecturas_edition_id'), table_name='lecturas', schema='app')
    op.drop_table('lecturas', schema='app')
    op.drop_index(op.f('ix_app_fuentes_catalogo_edition_id'), table_name='fuentes_catalogo', schema='app')
    op.drop_table('fuentes_catalogo', schema='app')
    op.drop_index(op.f('ix_app_obras_autores_author_id'), table_name='obras_autores', schema='app')
    op.drop_table('obras_autores', schema='app')
    op.drop_index(op.f('ix_app_entradas_biblioteca_work_id'), table_name='entradas_biblioteca', schema='app')
    op.drop_table('entradas_biblioteca', schema='app')
    op.drop_index(op.f('ix_app_ediciones_work_id'), table_name='ediciones', schema='app')
    op.drop_index(op.f('ix_app_ediciones_created_by_user_id'), table_name='ediciones', schema='app')
    op.drop_table('ediciones', schema='app')
    op.drop_index(op.f('ix_app_obras_created_by_user_id'), table_name='obras', schema='app')
    op.drop_table('obras', schema='app')
    op.drop_table('autores', schema='app')
    # ### end Alembic commands ###
